spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update

    datasource:
        url: jdbc:mysql://localhost:3306/controle_perguntas
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver